### PR TITLE
fix: implement findMany, deleteMany, and consumeOne on the tx adapter

### LINKED ISSUE #24: Firestore transactions require all reads to be executed before all writes. at ignore-listed frames
When I try to use secondaryStorage, it ends up throwing the following error:

```
2026-05-21T18:13:19.483Z ERROR [Better Auth]: Error Error: Firestore transactions require all reads to be executed before all writes.
    at ignore-listed frames

# SERVER_ERROR:
Error: Firestore transactions require all reads to be executed before all writes.
    at ignore-listed frames
```

It seems that when secondaryStorage is enabled, some Firestore transaction flow is performing a write before all reads are completed, which violates Firestore transaction rules.

### PR DESCRIPTION
**Pull request by creavenguo**
## The bug

PR #27 (closes #24) rewrote the transactional adapter with a buffered `TxBuffer` to fix Firestore's read-before-write ordering requirement, but the `txAdapter` object it builds inside `transaction()` only implements `create`, `update`, and `findOne`.

Better Auth's magic-link plugin consumes a verification token by calling `adapter.transaction()` and then, inside the callback, `txAdapter.findMany` (locate the latest token), `txAdapter.consumeOne` (read + delete atomically), and `txAdapter.deleteMany` (expired-token cleanup). None of these exist on the buffered `txAdapter`, so every magic-link verification throws:

```
TypeError: txAdapter.findMany is not a function
```

This is a regression from #27/#24 — magic-link sign-in worked before that rewrite (the old, unbuffered transaction wrapper apparently delegated to the full adapter), and broke silently afterward since the PR's test suite only covered the sign-up flow that #24 was about, not magic-link/verification.

## The fix

Extends `TxBuffer` and the `txAdapter` following the same pattern PR #27 established:

- **`findMany`**: reads via `transaction.get()` (chunked for oversized `in` clauses, like the non-tx path), overlays any staged update on top of each read doc, drops any doc with a staged delete, and additionally overlays matching staged creates from this same transaction — mirroring the existing `findOne`/`update` overlay logic. Supports `sortBy`/`limit`/`offset` like the non-tx `findMany`.
- **`deleteMany`**: stages deletes into the buffer rather than deleting immediately, consistent with how `create`/`update` already defer writes until `flush()`.
- **`consumeOne`**: read + stage-delete in one step, checking the buffer first for a matching staged create (mirrors `update`'s buffer-first lookup).
- **`TxBuffer.flush()`**: now handles the new `"delete"` op alongside `create`/`update`.
- **`findOne`**'s read overlay was also missing a check for staged deletes — it would return `{...staged.appData}` off of a delete entry (which has no `appData`) once one existed. Fixed as part of the same `TxBuffer` change, with `TxBufferEntry` now a discriminated union (`TxBufferWriteEntry | TxBufferDeleteEntry`) so this is caught at the type level going forward.

All reads still happen via `transaction.get()` before any `transaction.set`/`update`/`delete` — the read-before-write invariant from #27 is preserved; the new methods don't call `transaction.get()` after any write, and all actual Firestore writes (including deletes) remain confined to `flush()`, called once after the callback resolves.

## Tests

Added 6 tests to the existing `Transaction buffering (regression for #24)` block in `tests/index.test.ts`, run against the `user` model to isolate tx-adapter behavior from model-name resolution:

| Test | Covers |
|---|---|
| `findMany` inside a transaction returns matching Firestore-resident docs, sorted and limited | real-read path with `sortBy`/`limit` |
| `findMany` inside a transaction overlays a create staged earlier in the same transaction | buffered-create overlay |
| `consumeOne` inside a transaction returns the doc and deletes it on flush | read + deferred delete |
| `consumeOne` inside a transaction is invisible to a subsequent `findOne` in the same transaction | delete overlay on `findOne` |
| `deleteMany` inside a transaction removes all matching docs on flush | bulk deferred delete |
| throwing after `consumeOne` inside the callback aborts the transaction (doc survives) | rollback safety for the new delete op |

## Test results

```
Test Files  2 passed (2)
     Tests  29 passed (29)
```

23 from the existing suite + 6 new tests, all passing. Also ran `pnpm lint` and `pnpm build` clean.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by yultyyev** [comment]
Thanks @creavenguo, LGTM on the core fix.

I've stacked maintainer polish on your branch in #34 (verification model mapping, tx `deleteMany` buffered-create handling, native `consumeOne`, integration test). Once that's merged into your branch, I'll squash-merge everything to `main` as a single `fix(adapter): complete tx adapter verification support` release.

**Comment by creavenguo** [comment]
Glad to help

**Review by yultyyev — APPROVED** [review]
Thanks @creavenguo, LGTM. Correct fix for the #27 regression: magic-link verification needs `findMany` / `consumeOne` / `deleteMany` on the tx adapter, and this implements them without breaking the read-before-write buffer design. Tests cover the right cases.

Maintainer polish from #34 will follow in a separate release PR.
